# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eos',
                'doc_host': 'https://ai.github.io',
                'git_url': 'https://github.com/ai/eos',
                'lib_path': 'eos'},
  'syms': { 'eos.avatar': { 'eos.avatar.Avatar': ('01.avatar.html#avatar', 'eos/avatar.py'),
                            'eos.avatar.Avatar.__post_init__': ('01.avatar.html#avatar.__post_init__', 'eos/avatar.py'),
                            'eos.avatar.Avatar.agent': ('01.avatar.html#avatar.agent', 'eos/avatar.py'),
                            'eos.avatar.Avatar.can_server': ('01.avatar.html#avatar.can_server', 'eos/avatar.py'),
                            'eos.avatar.Avatar.driver': ('01.avatar.html#avatar.driver', 'eos/avatar.py'),
                            'eos.avatar.Avatar.infer_mode': ('01.avatar.html#avatar.infer_mode', 'eos/avatar.py'),
                            'eos.avatar.Avatar.resume': ('01.avatar.html#avatar.resume', 'eos/avatar.py'),
                            'eos.avatar.Avatar.trip_server': ('01.avatar.html#avatar.trip_server', 'eos/avatar.py'),
                            'eos.avatar.Avatar.truck': ('01.avatar.html#avatar.truck', 'eos/avatar.py'),
                            'eos.avatar.main': ('01.avatar.html#main', 'eos/avatar.py')},
            'eos.core': {'eos.core.foo': ('00.core.html#foo', 'eos/core.py')}}}
