# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eos',
                'doc_host': 'https://ai.github.io',
                'git_url': 'https://github.com/ai/eos',
                'lib_path': 'eos'},
  'syms': {'eos.core': {'eos.core.foo': ('core.html#foo', 'eos/core.py')}}}
