# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/eos',
                'doc_host': 'https://ai.github.io',
                'git_url': 'https://github.com/ai/eos',
                'lib_path': 'eos'},
  'syms': { 'eos.avatar': {},
            'eos.core': {'eos.core.foo': ('core.html#foo', 'eos/core.py')},
            'eos.suite.l045a-rdpg-suite': {},
            'eos.suite.l045a-suite': {},
            'eos.suite.l045a-transcribe': {},
            'eos.suite.realtime_ddpg_suite': {},
            'eos.suite.realtime_rdpg_suite': {},
            'eos.suite.rl_agent_suite': {},
            'eos.suite.rl_agent_suite-infer-ddpg-baseline': {},
            'eos.suite.rl_agent_suite-train-ddpg-baseline': {},
            'eos.tests.submodule.test_remotecan_get': {},
            'eos.tests.submodule.test_remotecan_pool': {}}}
